#!/usr/bin/env python3
"""
backtest_exec_alignment_delta.py — Compute PF/WR delta between legacy
`signal_close` entry and current `next_open` entry for the RSI-2 backtest.

Why: prior to v0.31.0 the backtest filled at close[D]; the live executor
fills at open[D+1]. This script runs the canonical RSI-2 conservative
backtest both ways and writes a markdown table comparing headline metrics
per symbol, plus an aggregate row.

Usage:
    source ~/.trading_env
    PYTHONPATH=scripts python3 scripts/backtest_exec_alignment_delta.py
    PYTHONPATH=scripts python3 scripts/backtest_exec_alignment_delta.py \\
        --symbols SPY QQQ NVDA --years 2 --out data/exec_alignment_delta.md
"""
import argparse
import os
import sys
from typing import List, Dict, Any

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from backtest_rsi2 import fetch_daily_bars, run_rsi2_backtest

DEFAULT_TIER1 = ["SPY", "QQQ", "NVDA", "XLK", "XLY", "XLI"]


def run_delta(symbols: List[str], years: int) -> List[Dict[str, Any]]:
    """Run both entry-timing modes per symbol, return one dict per symbol."""
    rows: List[Dict[str, Any]] = []
    for sym in symbols:
        try:
            data = fetch_daily_bars(sym, years)
        except Exception as e:
            rows.append({"symbol": sym, "error": str(e)[:120]})
            continue

        legacy = run_rsi2_backtest(
            data, sym,
            entry_timing="signal_close",
            strategy_name="RSI-2 (signal_close, legacy)",
        )
        current = run_rsi2_backtest(
            data, sym,
            entry_timing="next_open",
            strategy_name="RSI-2 (next_open, live-aligned)",
        )

        rows.append({
            "symbol": sym,
            "trades_old": legacy.total_trades,
            "trades_new": current.total_trades,
            "wr_old": legacy.win_rate,
            "wr_new": current.win_rate,
            "pf_old": legacy.profit_factor,
            "pf_new": current.profit_factor,
            "ret_old": legacy.total_return_pct,
            "ret_new": current.total_return_pct,
            "dd_old": legacy.max_drawdown_pct,
            "dd_new": current.max_drawdown_pct,
        })
    return rows


def write_markdown(rows: List[Dict[str, Any]], out_path: str, years: int) -> None:
    """Write a markdown comparison report to out_path."""
    lines = [
        "# Backtest Execution Alignment Delta",
        "",
        "_RSI-2 conservative backtest run two ways: legacy `signal_close` "
        "entry (fill at `close[D]`) vs current `next_open` entry "
        "(fill at `open[D+1]`). `next_open` matches live executor behavior — "
        "screener emits EOD at `close[D]`; executor fills the next morning. "
        "The legacy mode reproduces the pre-v0.31.0 bug for delta studies. "
        "Generated by `scripts/backtest_exec_alignment_delta.py`._",
        "",
        f"**Lookback:** {years} year(s). **Universe size:** {len(rows)} symbols.",
        "",
        "| Symbol | Trades (old → new) | Win % (old → new) | PF (old → new) "
        "| Return % (old → new) | Max DD % (old → new) |",
        "|--------|--------------------|-------------------|----------------"
        "|----------------------|----------------------|",
    ]
    for r in rows:
        if "error" in r:
            lines.append(
                f"| {r['symbol']} | ⚠ {r['error']} | — | — | — | — |"
            )
            continue
        lines.append(
            f"| {r['symbol']} "
            f"| {r['trades_old']} → {r['trades_new']} "
            f"| {r['wr_old']:.1f} → {r['wr_new']:.1f} "
            f"| {r['pf_old']:.2f} → {r['pf_new']:.2f} "
            f"| {r['ret_old']:+.1f} → {r['ret_new']:+.1f} "
            f"| {r['dd_old']:.1f} → {r['dd_new']:.1f} |"
        )

    valid = [r for r in rows if "error" not in r]
    if valid:
        avg = lambda key: sum(r[key] for r in valid) / len(valid)
        lines += [
            "",
            "## Aggregate",
            "",
            f"- Avg Win Rate: {avg('wr_old'):.1f}% → {avg('wr_new'):.1f}% "
            f"({avg('wr_new') - avg('wr_old'):+.1f} pts)",
            f"- Avg Profit Factor: {avg('pf_old'):.2f} → {avg('pf_new'):.2f} "
            f"({avg('pf_new') - avg('pf_old'):+.2f})",
            f"- Avg Total Return: {avg('ret_old'):+.1f}% → "
            f"{avg('ret_new'):+.1f}%",
            f"- Avg Max Drawdown: {avg('dd_old'):.1f}% → "
            f"{avg('dd_new'):.1f}%",
        ]
    lines.append("")
    lines.append(
        "_Methodology: identical strategy parameters except entry mechanic. "
        "Stop-loss is computed off the entry price, so stop levels also "
        "differ between modes — this is intentional and matches the live "
        "stop placement at fill time._"
    )

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Backtest execution-alignment delta report"
    )
    parser.add_argument("--symbols", nargs="+", default=DEFAULT_TIER1,
                        help="Symbols to compare (default: Tier 1)")
    parser.add_argument("--years", type=int, default=2,
                        help="Years of history (default: 2)")
    parser.add_argument("--out", default="data/exec_alignment_delta.md",
                        help="Output markdown path")
    args = parser.parse_args()

    print(f"Running delta on {len(args.symbols)} symbols × {args.years}y...")
    rows = run_delta(args.symbols, args.years)
    write_markdown(rows, args.out, args.years)
    print(f"Wrote {args.out} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
